on:
  push:
    branches:
    - dev

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: 'ssh.strato.de'
        port: 22
        username: 'dev-tempus@josuadev.de'
        password: 'jahbe2-wesxiN-zakfix'
        localPath: './'
        remotePath: './'
